/*
 *  File name: irq.c
 *  File Description: This file defines the LETIMER0_IRQHandler that drives the LED based on the COMP1 and UF bits
 *  Date: 14-Sep-2023
 *  Author: Visweshwaran Baskaran viba5388@colorado.edu
 *  Reference:
 *    [1] ECEN5813 IOT Embedded Firmware lecture slides week 2-3
 */

#include "irq.h"

/*
 * @brief This is the interrupt service routine for the LETIMER0 peripheral. It handles interrupts generated by LETIMER0, manages specific interrupt flags, and controls LED status based on interrupt conditions.
 *
 */
void LETIMER0_IRQHandler(void)
{
  CORE_DECLARE_IRQ_STATE;
  CORE_ENTER_CRITICAL();

  uint32_t flag;
  flag = LETIMER_IntGetEnabled(LETIMER0);
  LETIMER_IntClear(LETIMER0,flag);
  CORE_EXIT_CRITICAL();


  if(flag & LETIMER_IF_UF)
    {
      gpioLed0SetOff();
    }
  else if (flag & LETIMER_IF_COMP1)
    {
      gpioLed0SetOn();
    }
}

